package main

import (
	"fmt"
	"io"

	"github.com/koron-go/srcdom"
)

func generateMockType1(w io.Writer, mockTag, mockTypn, mockPkgn string, typ *srcdom.Type, pkg *srcdom.Package) error {
	origTypn := pkg.Name + "." + typ.Name
	methods := filterMethods(typ.Methods, mockTypn)
	if len(methods) == 0 {
		return fmt.Errorf("no methods in type:%s", typ.Name)
	}

	// write headers.
	if !forTest {
		fmt.Fprintf(w, "// +build %s\n\n", mockTag)
	}
	fmt.Fprintf(w, "// Code generated by github.com/koron/mockgo; DO NOT EDIT.\n\n")
	fmt.Fprintf(w, "package %s\n\n", mockPkgn)

	// write the mock type.
	fmt.Fprintf(w, "// %s is a mock of %s for test.\n", mockTypn, origTypn)
	fmt.Fprintf(w, "type %s struct {\n", mockTypn)
	for _, m := range methods {
		fmt.Fprintf(w, "\t%s_Ps []*%s\n", m.name, m.pname())
		fmt.Fprintf(w, "\t%s_Rs []*%s\n", m.name, m.rname())
	}
	fmt.Fprintf(w, "}\n")

	for _, m := range methods {
		fmt.Fprintf(w, "\n")

		// write parameter type for the method.
		fmt.Fprintf(w, "// %s packs input parameters of %s#%s method.\n", m.pname(), origTypn, m.name)
		fmt.Fprintf(w, "type %s struct {\n", m.pname())
		for _, a := range m.args {
			typ := toStructType(a.typ)
			fmt.Fprintf(w, "\t%s %s\n", toPub(a.name), typ)
		}
		fmt.Fprintf(w, "}\n\n")

		// write result type for the method.
		fmt.Fprintf(w, "// %s packs output parameters of %s#%s method.\n", m.rname(), origTypn, m.name)
		fmt.Fprintf(w, "type %s struct {\n", m.rname())
		for _, r := range m.rets {
			fmt.Fprintf(w, "\t%s %s\n", r.name, r.typ)
		}
		fmt.Fprintf(w, "}\n\n")

		// write mock func for the method.
		fmt.Fprintf(w, "// %s is mock of %s#%[1]s method.\n", m.name, origTypn)
		fmt.Fprintf(w, "func (_m *%s) %s(%s) (%s) {\n", mockTypn, m.name, m.args.nameTypes(), m.rets.types())
		fmt.Fprintf(w, "\t_m.%s_Ps = append(_m.%[1]s_Ps, &%s{%s})\n", m.name, m.pname(), m.args.names())
		fmt.Fprintf(w, "\tvar _r *%s\n", m.rname())
		fmt.Fprintf(w, "\t_r, _m.%[1]s_Rs = _m.%[1]s_Rs[0], _m.%[1]s_Rs[1:]\n", m.name)
		fmt.Fprintf(w, "\treturn %s\n", m.rets.namesPrefix("_r"))
		fmt.Fprintf(w, "}\n")
	}
	return nil
}
