//go:build mock
// +build mock

// Code generated by github.com/koron/mockgo; DO NOT EDIT.

package mock1_gen2

import "github.com/koron/mockgo/mockrt"

// Foo is a mock of pkg1.Foo for test.
type Foo struct {
	Q *mockrt.Sequence
}

// FooHello_P packs input parameters of pkg1.Foo#Hello method.
type FooHello_P struct {
	Name string
}

// FooHello_R packs output parameters of pkg1.Foo#Hello method.
type FooHello_R struct {
	Out0 error
}

// Hello is mock of pkg1.Foo#Hello method.
func (_m *Foo) Hello(name string) error {
	_m.Q.T().Helper()
	_r := (_m.Q.Call("Foo.Hello", FooHello_P{name})).(FooHello_R)
	return _r.Out0
}
