//go:build mock
// +build mock

// Code generated by github.com/koron/mockgo; DO NOT EDIT.

package mock1_gen1

// Foo is a mock of pkg1.Foo for test.
type Foo struct {
	Hello_Ps []*FooHello_P
	Hello_Rs []*FooHello_R
}

// FooHello_P packs input parameters of pkg1.Foo#Hello method.
type FooHello_P struct {
	Name string
}

// FooHello_R packs output parameters of pkg1.Foo#Hello method.
type FooHello_R struct {
	Out0 error
}

// Hello is mock of pkg1.Foo#Hello method.
func (_m *Foo) Hello(name string) error {
	_m.Hello_Ps = append(_m.Hello_Ps, &FooHello_P{name})
	var _r *FooHello_R
	_r, _m.Hello_Rs = _m.Hello_Rs[0], _m.Hello_Rs[1:]
	return _r.Out0
}
