// Code generated by github.com/koron/mockgo; DO NOT EDIT.

//go:build mock
// +build mock

package mock1_gen3

import "github.com/koron/mockgo/mockrt3"

// Foo is a mock of pkg1.Foo for test.
type Foo struct {
	Q *mockrt3.Q
}

// FooHello_P packs input parameters of pkg1.Foo#Hello method.
type FooHello_P struct {
	Name string
}

// P__ implements mockrt3.P interface
func (FooHello_P) P__() {}

// FooHello_R packs output parameters of pkg1.Foo#Hello method.
type FooHello_R struct {
	Out0 error
}

// R__ implements mockrt3.R interface
func (FooHello_R) R__() {}

// Hello is mock of pkg1.Foo#Hello method.
func (_m *Foo) Hello(name string) error {
	_m.Q.T().Helper()
	_r := (_m.Q.Call("Foo.Hello", FooHello_P{name})).(FooHello_R)
	return _r.Out0
}
